### PR TITLE
[Issue 60] Created index.ipynb notebook to guide through the example …

### LINKED ISSUE #60: Top level index.ipynb guide to all demo / test notebooks
We've got a slew of content. Users need a roadmap. This should be something like the index.ipynb we put on jupyter.cloudet.xyz but specific to all the notebooks in this repo. The guide should suggest a sequence of reading through them to learn about dashboards and give a brief description of each to avoid having the user open each one to learn what it is.

### PR DESCRIPTION
**Pull request by dalogsdon**
…notebooks.

Fixes #60 

:chicken:

### CODE REVIEW

**Comment by parente** [comment]
This is a great ToC. I wonder now where the 3-step intro of code-layout-view should go. Maybe this notebook itself has those instructions? Or since the scotch one is the first on the list, it needs to become more of a tutorial? What do you guys think?

**Comment by dalogsdon** [comment]
I like the idea of the index notebook being a "home page" for the dashboard examples. As such, it could contain that info and any other vital information about dashboards (how to deploy?).

We could potentially also put demo-specific information in the demo notebooks. The code-layout-view information could go in the scotch notebook to serve as a reminder since it is first. I don't know if deploy or anything else needs to go in any specific notebook or can just reside in the index notebook.

**Comment by parente** [comment]
I think having the basic 1-2-3 tutorial in the index notebook is good. Let's do that as part of this PR. Maybe right at the top before the examples. 

I also agree we should dress up the scotch one more. We can do that as a separate PR against the same issue if you want to tackle it.

Deploy is a bit tricky because anything other than local deploy is still alpha at best. The README in this project has a bit section at the bottom about all the caveats. I'd hate to have to reproduce that in every notebook. But that said, maybe there's a sweet spot that we can hit with local deploy + download and follow the included README?

**Comment by jhpedemonte** [comment]
Added a usage section at top.

**Pull request merged**
