### PR TITLE
[Issue 88] Fix arrows in Upcoming Meetups element.

### LINKED ISSUE #88: Meetup outreach 'change in last week' arrow no longer renders
Since moving the 'Upcoming Meetups' widget into an external Polymer element, the arrows no longer render since they are Font Awesome characters. We could change them to Unicode arrows to avoid including Font Awesome in the Polymer Element.

### PR DESCRIPTION
**Pull request by jhpedemonte**
Instead of importing Font Awesome into our new Polymer element,
let's just use unicode.

Fixes #88 

:cow:

### CODE REVIEW

**Comment by parente** [comment]
Can you switch to the unicode char code like `content: "\2193"`? Safer bet when servers, editors are misconfigured or old.

**Comment by dalogsdon** [comment]
Yeah we can change it. I had originally tried that, but the reference site I was using had the wrong code, so I was lazy and copied the character directly. :stuck_out_tongue: 

looks like it is **"\2b06"** and **"\2b07"**

**Comment by parente** [comment]
OK. Will wait to merge.

**Comment by dalogsdon** [comment]
They have been replaced with codes.

**Pull request merged**
