### PR TITLE
[Issue 57] Handle resize directly in upcoming meetups element.

### PR DESCRIPTION
**Pull request by jhpedemonte**
Revert `Polymer.dom` call when handling events.
Add resizing check to upcoming meetups Polymer element.

:chicken:

### CODE REVIEW

**Comment by parente** [comment]
1. This PR branch.
2. Run notebook one cell at a time, making sure all widgets load before proceeding.
3. Switch to layout view.
4. Table is mis-rendered.
5. Resize browser and it fixes itself (but I shouldn't have to).

screen shot 2015-11-02 at 11 15 59 am

**Comment by jhpedemonte** [comment]
@lbustelo @deedubbu

Not sure how we didn't run into this before, but there is a problem caused by widgets returning 404.

We have the following HTML cell:

```html
<link rel="import" href="urth_components/iron-list/iron-list.html"
    is="urth-core-import" package="PolymerElements/iron-list">
<link rel="import" href="urth_components/paper-toggle-button/paper-toggle-button.html"
    is="urth-core-import" package="PolymerElements/paper-toggle-button#v1.0.10">
<link rel="import" href="urth_components/paper-material/paper-material.html"
    is="urth-core-import" package="PolymerElements/paper-material">
<link rel="import" href="./dynamic-list.html">
<link rel="import" href="./upcoming-meetups.html">
```

`iron-list` imports `iron-resizable-behavior`, which we use in `upcoming-meetups`. However, on first load, `iron-list` comes back as 404, `upcoming-meeups` is loaded but with this warning:

```
[upcoming-meetups::_flattenBehaviorsList]: behavior is null, check for missing or 404 import
```

since `iron-resizable-behavior` hasn't been loaded yet. Finally, `iron-list` (and `iron-resizable-behavior`) are loaded, but that doesn't affect `upcoming-meetups` which has already failed. Later, when we try to resize by calling a function from `iron-resizable-behavior`, we get an undefined error.

I guess one workaround would be to explicitly import `iron-resizable-behavior`, even though `iron-list` should take care of that for us. Not returning 404 would be the best solution to this, though.

**Comment by jhpedemonte** [comment]
Another update. Implemented workaround as described in previous comment and had to invoke a callback async.

**Comment by parente** [comment]
Tested and confirmed it resizes properly now.

**Pull request merged**
