### PR TITLE
Add initial Sphinx documentation

### PR DESCRIPTION
**Pull request by willingc**
This adds basic documentation in Sphinx using the README of the repo as the source of documentation content. It uses the default ReadTheDocs theme; provides conda support; allows rst and markdown source files.

A test rendering of the docs is available here: http://test-dashboards.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by parente** [comment]
@willingc you didn't have to rush to do that but thank you all the same.

My comments on the call yesterday were about whether Sphinx doc even makes sense for a tiny little extension such as this one. There's already inline user help when they flip to dashboard mode

screen shot 2016-06-29 at 7 48 50 am


Most of the interface is pretty straightfoward: you grab handles to drag/drop and resize cells. 

screen shot 2016-06-29 at 7 49 17 am


I was going to raise the question of what level of doc these things demand on the enhancement proposal PR when someone brought it up. But while I have you here, do you have any thoughts?

**Comment by willingc** [comment]
@parente No worries, I recognize that you weren't asking yesterday for me to do this. This took about 1/2 hour for me to put together so I just went ahead and added them so docs wouldn't be a roadblock to graduation since I personally think the dashboards are cool and should graduate ;-)

As for your question of what level of documentation, I think it probably depends on the project. For Dashboards, I think that the help and guidance built into the extension provide much of the documentation needed for the end user. I would recommend that the documentation on ReadTheDocs cover essentially what is in the README with focus on the following goals:

- discoverability for users familiar with ReadTheDocs
- key features of the extension
- why and when an end user would use the Dashboards extension
- installation instructions
- basic how to get started using the extension (this can be as simple as guiding them to the extension's help)

**Comment by parente** [comment]
@willingc Your bulleted list sounds like a good first target.

**Comment by parente** [comment]
Folded these commits into #269.

**Pull request closed without merging**
