### PR TITLE
[issue: 200] Fix bokeh inline JS

### LINKED ISSUE #200: Bokeh demo error when doing `run all`
The default behavior of Bokeh is to load JS resources from a CDN when running `output_notebook()` with no arguments. This causes a comm-related error when `show()` is run before the JS files are loaded.

One solution is to put Boken in inline mode using `output_notebook(bokeh.resources.INLINE)` or setting the environment variable `BOKEH_RESOURCES=inline` when running the notebook server. See https://github.com/bokeh/bokeh/issues/3639#issuecomment-184251673.

### PR DESCRIPTION
**Pull request by parente**
Fixes #200

### CODE REVIEW

**Comment by parente** [comment]
@dalogsdon Can you review and merge? Run All works fine for me 5 times in a row with kernel restart in between.

**Comment by dalogsdon** [comment]
Do you want to put some notes about the inline mode in the notebook since it is required for dashboards to work?

**Comment by parente** [comment]
Doh, yes. I did suggest that didn't I.

**Comment by dalogsdon** [comment]
Other than that, it looks good and works. This is pretty much exactly what I did while investigating Bokeh.

**Comment by parente** [comment]
@dalogsdon All set.

**Pull request merged**
