### PR TITLE
[Issue 259] Update example/test notebooks to new metadata spec.

### LINKED ISSUE #259: Update example & test notebooks to latest metadata spec

### PR DESCRIPTION
**Pull request by dalogsdon**
Fixes #259

### CODE REVIEW

**Comment by parente** [comment]
Can you take a crack at updating the text in index.ipynb too? It's terribly out of date.

**Comment by dalogsdon** [comment]
I updated the index.ipynb to add a section on layout and update UI references. It still contains all the demos. If desired, I can add some inline pictures of toolbars, grid layout cell controls, etc. to clarify some steps.

It has a section on downloading, but it is missing a section on deploying. Should we add that?

**Comment by parente** [comment]
I'd whack the deploying/downloading section and just point to https://github.com/jupyter-incubator/dashboards/wiki which talks about the end-to-end workflow, points to all the necessary components, and links to the dashboards_setup repo for various ways to bring up all the required infrastructure. The focus of the index.ipynb should be a very lightweight intro to using the dashboard layout extension in the notebook, primarily, since it resides in this repo.

I wouldn't even add new pics. I think putting up a proper doc site is going to be one of the steps we have to take as we graduate out of incubator like we did for kernel gateway. That'll be the time and place to do a better job.

**Comment by dalogsdon** [comment]
Updated to point to wiki for details on deploying/downloading.

**Pull request merged**
