### PR TITLE
[Issue 118]: Added python 2.7 support

### PR DESCRIPTION
**Pull request by Lull3rSkat3r**
(c) Copyright IBM Corp. 2015

### CODE REVIEW

**Comment by Lull3rSkat3r** [comment]
Letting the changes go through travis to make sure the make targets run successfully for python 2 and 3. I still need a commit with changes to docs to show to interact with 2.7 support.

**Comment by Lull3rSkat3r** [comment]
@parente, do we want to add 2.7 support to the `demo` target as well?

**Comment by parente** [comment]
Don't bother with the demo target. Looks like all the tests have passed. I'll try it and merge.

**Comment by Lull3rSkat3r** [comment]
Pushed a fix for a make target error. Branch is all good to go.

**Comment by parente** [comment]
Looks like the version PR that went in ahead caused a conflict. Can you rebase off master?

**Comment by Lull3rSkat3r** [comment]
Rebased.

**Comment by parente** [comment]
Can you update the README bullet that says:

> * IPython Notebook 3.2.x (not Jupyter Notebook 4.x, yet) running on Python 3.x

to say "Python 3.x or 2.7.x"

**Comment by Lull3rSkat3r** [comment]
@parente, added the change.

**Pull request merged**
