### PR TITLE
[issue 14]: Initial prototype of sentiment dashboard

### PR DESCRIPTION
**Pull request by Lull3rSkat3r**
Creates a dashboard for analyzing community sentiment around open source projects.

### CODE REVIEW

**Comment by Lull3rSkat3r** [comment]
Still need to add streaming. I will update when streaming is included.

**Comment by parente** [comment]
Need a title at the top and a couple sentence summary of what it does for notebook mode. I know the text for the UI is in there, but it's wayyyyyy down.

In cell #2:

`./static/` is no longer correct. Check what all the other notebooks are doing to account for the change in widgets.

In cell #8:

`IndentationError: unindent does not match any outer indentation level`

Make a comment on the terrible time.sleep hack. Point to a widgets issue about it if possible.

When clicking "Collect Data", nothing happens and I get `Uncaught TypeError: get_individual_sentiment_data.invoke is not a function` in the JS console.

**Comment by parente** [comment]
Extra blank bullet under "Positive" header.

**Comment by parente** [comment]
And you may have pushed your private GitHub key.

**Comment by Lull3rSkat3r** [comment]
The only thing I am not able to fix is the `Uncaught TypeError: get_individual_sentiment_data.invoke is not a function`. If I run all the cells in notebook view, or dashboard view everything is fine. The only time I encounter an error is when I switch between the two. The specific steps to reproduce are:
 1. Running all the cells in the notebook view
 1. Switching to Dashboard view
 1. Filling out the form for org/repo and clicking _Collect Data_

There is a branch that needs to be merged into declarativewidgets for the historical `urth-viz-chart` to work correctly with the dates. I will get with @peller to see about merging [his branch](https://github.com/peller/declarativewidgets/tree/chart-column-type).

I am now seeing problems with `channel` not being defined client side. Looking into that now.

**Comment by parente** [comment]
So having the thing go missing between switch to layout and dashboard view is odd. Do you see an re-init messages in the console? AFAIK, there's no add/remove of DOM nodes so things shouldn't go missing.

/cc @lbustelo @jhpedemonte

**Comment by Lull3rSkat3r** [comment]
So after switching views I looked at the value for `get_total_sentiment_data` and `get_total_sentiment_data`. They have been changed into arrays of dom elements ⊙_ʘ. Trying to figure out where that change is coming from.
screen shot 2015-10-20 at 8 56 48 am

**Comment by Lull3rSkat3r** [comment]
Figured out my channel issue. Moved some code around and didn't have enough :coffee: to realize I moved python code into a `<script>` tag.

**Comment by parente** [comment]
:8ball:

**Comment by parente** [comment]
Remaining issues that need to be fixed before we can merge this:

1. Why does jupyter-incubator/declarativewidgets#36 cause path issues? We need it to make the historical plot widget work properly.
2. Why does running in notebook view then switching to dashboard view cause this weirdness: https://github.com/jupyter-incubator/dashboards/pull/37#issuecomment-149576470

**Comment by parente** [comment]
I tested with jupyter-incubator/declarativewidgets#53 and seems to work. I've got a few nits of things to fix in the next PR that I'll put in the issue.

Waiting for jupyter-incubator/declarativewidgets#53 to merge so this will work properly when it goes in.

**Comment by lbustelo** [comment]
jupyter-incubator/declarativewidgets#53 is merged

**Comment by parente** [comment]
:shipit:

**Pull request merged**
