### PR TITLE
Update Notebooks to be compatible with declwidgets 0.6.0

### LINKED ISSUE #249: Update all demos for 0.6.0 decl widgets compatibility
* [x] Manually init the widgets (see https://github.com/jupyter-incubator/declarativewidgets/pull/295)
* [x] Put a markdown note in every demo notebook about what version it's compatible with

### PR DESCRIPTION
**Pull request by jhpedemonte**
Fixes #249

### CODE REVIEW

**Comment by parente** [comment]
Not sure why there's a merge conflict unless this is in an old branch. When you rebase, I'll give it a test.

**Comment by parente** [comment]
Tested. Need to add an init call to `test_layout_declarativewidgets`. Everything else seemed to work fine, #263 aside.

**Comment by jhpedemonte** [comment]
Thanks, @parente. Updated that file as well.

**Comment by parente** [comment]
🍰

**Pull request merged**
