### PR TITLE
Add Sphinx source for ReadTheDocs site

### PR DESCRIPTION
**Pull request by parente**
Adds one commit to PR #265 to refactor the one large doc page into multiple RTD pages. Cleans up some of the dev and doc building process along the way. Adds one step-by-step guide with screenshots showing the main features.

Does **not** simplify the README.md yet. We need the doc site to go live *before* we tear all of the information out of the README. I'll do that after this PR goes in and to complete #266.

### CODE REVIEW

**Comment by parente** [comment]
@willingc, @jhpedemonte, @dalogsdon can you all take a look when you get a chance?

@willingc: I setup jupyter-dashboards-layout.readthedocs.org and enabled the webhook here.

**Comment by parente** [comment]
To aid code review, here's the rendered docs on a temporary staging site:

http://jupyter-dashboards-layout-staging.readthedocs.io/en/add-rtd/

**Comment by willingc** [comment]
@parente Looks good. Good call on the last commit. We can work on travis at a later date.

**Comment by dalogsdon** [comment]
Docs look pretty good.

**Comment by willingc** [comment]
Push the green button @parente ;-)

**Pull request merged**
