### PR TITLE
[issue 123] View menu items and toolbar switcher should use consistent naming

### PR DESCRIPTION
**Pull request by nitind**
Take "view" out of the view menu's actions. For #123.

(c) Copyright IBM Corp. 2015

### CODE REVIEW

**Comment by nitind** [comment]
For #123.

**Comment by parente** [comment]
@jhpedemonte @dalogsdon 

The toolbar buttons next to the View: label have tooltips that start with "Notebook view", "Layout view" and "Dashboard view". This PR changes the View menu items to "Notebook", "Layout", and "Dashboard" for consistency.

What do you think? I know we bikeshed on the menu items before, but this does make it more consistent.

**Comment by nitind** [comment]
image
Second commit gives our entries in the View menu tooltips as well, reusing the help text from the toolbar buttons.

**Comment by dalogsdon** [comment]
The only thing is that "Layout" is a bit vague, especially with "Dashboard" right beside it. It may be tempting to immediately go to "Dashboard" and then be confused.

One solution to keep consistency with the show/hide menu items would be to put a "Dashboard" sub-menu under "View" menu with the items "Notebook", "Layout", and "Preview". The corresponding toolbar button could also change to "Preview" as well.

**Comment by parente** [comment]
> The only thing is that "Layout" is a bit vague, especially with "Dashboard" right beside it. It may be tempting to immediately go to "Dashboard" and then be confused.

Does this problem already exist with the toolbar buttons? Their tool tips say Notebook view, Layout view, Dashboard view.

I'd avoid the submenu here just because the view menu is already really short. The double level of menu nav will irk me when I want to go back to notebook view from the dashboard preview.

**Comment by nitind** [comment]
Hopefully being on the View menu is enough context, particularly since Dashboard->Notebook would also be confusing. I'd rather avoid burying them in a submenu just so we could have consistent labelling. If you really think the change is too vague, I would prefer leaving the menu items as they are.

**Comment by dalogsdon** [comment]
I agree that a submenu would not be great in a short menu, but View > Layout is vague. How about this:

View menu has the 3 options "Notebook", "Dashboard Layout", "Dashboard Preview". Then update the tooltips of the toolbar buttons to contain those words like "Notebook View. Layout the code." while the tooltips of the menu items don't contain the first part, just "Layout the code." for the Notebook menu item.

**Comment by parente** [comment]
Works for me.

**Comment by nitind** [comment]
Same here. New commit added.

**Comment by parente** [comment]
@nitind Either GitHub is not showing me the right file delta again or we're still mismatched.

Here's the roll-up of everything above.

From @dalogsdon above, the menu item labels (not in parentheses) and tooltips (in parentheses) should be:

* Notebook (Edit the code)
* Dashboard Layout (Size and position dashboard cells)
* Dashboard Preview (Preview the dashboard)

And the toolbar button tooltips should be:

* Notebook view. Edit the code.
* Dashboard Layout. Size and position dashboard cells.
* Dashboard Preview. Preview the dashboard.

**Comment by parente** [comment]
Good enough.

**Pull request merged**
