### PR TITLE
[Issue 30] New Meetup Streaming demo, with business scenario

### PR DESCRIPTION
**Pull request by jhpedemonte**
Streaming demo notebook which aids in promoting a set of
upcoming Meetups by contacting candidates pulled from RSVP
stream.

### CODE REVIEW

**Comment by parente** [comment]
Well, dang, I can't comment on the diff because it's too big.

A few things to fix:

* Comments near vars should be # syntax, not '''
* Any ''' comments above functions should be in the functions as docstrings  (https://en.wikipedia.org/wiki/Docstring#Python)
* That collect call that you had to switch to has me a bit worried. It's pulling everything back to the driver. Can you confirm it's only pulling back what was fetched in the window of time since the last pul from the stream?

After these, I'll take an add comments editing pass through like last time, once it's in master.

**Comment by jhpedemonte** [comment]
Fixed comments. The `collect` is only returning the contents of the latest RDD, because we're doing a `<dstream>.foreachRDD`.

We'll need to rethink how this notebook is laid out, since it makes heavy use of globals. Will need to use map/reduce or broadcast vars & accumulators.

**Comment by parente** [comment]
Do you want to tackle those improvements in a follow on or now?

**Comment by parente** [comment]
Putting aside the dashboard deployment (issue #38) and timing issues (jupyter-incubator/declarativewidgets#25), I think this is fine to go in with a bit more verbage around the code. I'm willing to make the few edits I have in a mind. I'm not too worried about reorganizing the notebook in this go around to use broadcast vars, accumulators, etc. I'm planning on putting in the same note we had in the other streaming demo to the effect of "this is a demo, not the way you'd build a production system".

@jhpedemonte, @dalogsdon are you guys cool with passing me the pen for the text edits? If so, I suggest tackling the smallish change for #38 and opening one or more follow-on issues (labeled enhancements) if you have solid ideas about how to take this notebook further.

**Comment by jhpedemonte** [comment]
@parente, passing it on to you. I've opened a separate issue (issue #39) to handle our use of globals.

**Pull request closed without merging**
