### PR TITLE
Update meetup streaming demo dashboard to work with resizable globe

### PR DESCRIPTION
**Pull request by jhpedemonte**
The webgl-globe element is now using the resize events that the Dashboard publishes as part of [PR 16](https://github.com/jupyter-incubator/dashboards/pull/16). This PR updates the streaming demo layout to make better use of a smaller globe.

### CODE REVIEW

**Comment by parente** [comment]
Fresh notebook in the PR renders like this when flipping to layout mode w/ PR #12 in place. Something amiss?

screen shot 2015-10-05 at 9 50 18 pm

**Comment by dalogsdon** [comment]
It looks like the card is too wide before it gets data. We may need to update the styling so it is more consistent in its empty state.

**Comment by parente** [comment]
Sure. Just push a new commit on this branch when you've got it.

**Comment by dalogsdon** [comment]
Looks like the paper-card we use in the notebook was a fixed width designed for the widest notebook size. We don't have great dashboard support for the responsive design of the notebook, but we did add some more flexible styling to the card to cope with smaller notebook widths.

**Pull request merged**
