### PR TITLE
Moved `dynamic-list` out of meetup outreach notebook.

### LINKED ISSUE #58: Meetup Outreach table problems
Columns are not aligned. Dates appear to be missing.

screen shot 2015-10-27 at 9 06 49 am

### LINKED ISSUE #71: Move dynamic list widget out of outreach notebook
Continuation of #59. Move the dynamic list widget out of the meetup outreach notebook and use the association markup to get it packaged with the notebook / dashboard. Requires a fix on the widget side.

### PR DESCRIPTION
**Pull request by dalogsdon**
Also created a new Polymer element for upcoming meetups list and externalized it as well.

Fixes #71
Fixes #58 

:chicken:

### CODE REVIEW

**Comment by dalogsdon** [comment]
Currently deploying doesn't work because we are installing Polymer 1.2 when deploying.

(see https://github.com/jupyter-incubator/declarativewidgets/issues/62)

**Comment by parente** [comment]
So we shouldn't merge this until the deploy works.

**Comment by dalogsdon** [comment]
The deploy issue is unrelated to the Meetup outreach notebook changes. It happens with the current version as well.

**Comment by parente** [comment]
Can you test again now that widgets moved to 1.2 to make sure everything works correctly when deployed?

**Comment by dalogsdon** [comment]
It is working now with the widgets update to Polymer 1.2.

**Pull request merged**
